<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Editamos un Trabajador de Mediweb ❤️</h1>

    <form action="../Controller/ActualizarTrabajadorController.php" method="POST">
        <?php foreach ($datos as $trabajador): ?>
            <input type="hidden" name="id" id="id" value="<?= $trabajador['id'] ?>">
            <label for="nombre">Nombres: </label>
            <input type="text" name="nombre" id="nombre" value="<?= $trabajador['nombre'] ?>"><br>
            <label for="apellido">Apellidos: </label>
            <input type="text" name="apellido" id="apellido" value="<?= $trabajador['apellido'] ?>"><br>
            <label for="dni">DNI: </label>
            <input type="number" name="dni" id="dni" value="<?= $trabajador['dni'] ?>"><br>
            <label for="celular">Celular: </label>
            <input type="number" name="celular" id="celular" value="<?= $trabajador['celular'] ?>"><br>
        <?php endforeach ?>
        <a href="./TrabajadorController.php">Cancelar</a>
        <button>Guardar</button>
    </form>

</body>
</html>